<a href="https://colab.research.google.com/github/trannolis/data/blob/main/Numpy%2BAssignment_Nick_Tran.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy Assignment

Numpy is a library for numerical computing.

This assignment covers the important numpy commands which will be used in all the programming assignments for this course. 

Basics: NumPy’s main object is the homogeneous multidimensional array. It is a table of elements (usually numbers), all of the same type, indexed by a tuple of positive integers. In NumPy dimensions are called axes. The number of axes is rank.
For example, the coordinates of a point in 3D space [1, 2, 1] is an array of rank 1, because it has one axis i.e. just a single row. That axis has a length of 3. 

# Array Creation

Numpy arrays behave similar to n-dimensional matrices in matlab.

There are several ways to create an array: Two methods are shown below. Before moving ahead, lets first import numpy.  

In [3]:
# Just run this code cell by pressing shift+enter
import numpy as np

In [4]:
# Method 1 for creating an array: passing a list of numbers.
a=np.array([3,6,2])
print(a)

[3 6 2]


In [5]:
# Create an array b having elements 9,6,3,1. 
# In the code below, remove None and write the numpy command to create an array having these elements. 
b = None
print(b)

None


 If you simply pass numbers as attributes, this will give an error. example: np.array(9,6,3,1) will give an error. Try it yourself in the code cell below.

In [9]:
b = np.array(9,6,3,1)

TypeError: ignored

Array transforms sequences of sequences into two-dimensional arrays. Sequences of sequences of sequences into three-dimensional arrays, and so on. Run example below which is a 2-dimensional array.

In [8]:
c = np.array([[1,2,3],[4,5,6]])
print(c)

[[1 2 3]
 [4 5 6]]


Example of 3-dimensional array:

In [ ]:
# Just run this code cell: 
c = np.array([[[1,2,3],[4,5,6]],[[6,7,8],[9,10,11]]])
print(c)

In [ ]:
# Create a 2-dimensional array having elemnets [15,16,17] in the first row and [18,19,20 ] in the second row.
c = None
print(c)

Method 2 for creating an array: using the "arange" function.  Numpy has a function called arange which is analogous to range function of python. arange function returns array instead of list. Example shown below.

In [12]:
# Run this code cell
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [13]:
# Run this code cell
b = np.arange(1,10,2)
# Creates an array of 1-dimension. The array values starts at 1, increments by 2 upto 10 (but not including 10). 
print(b)

[1 3 5 7 9]


In [ ]:
# Create 1-d array using arange having elements from 1 to 15
c = None
print(c)

# Important attributes of the array object.
Attribute description is given in the comments of the respective code cells.


In [ ]:
# Run this cell
a = np.array([[1,2,3],[4,5,6]])
print(a)

In [ ]:
# ndarray.ndim gives the number of axes(dimensions) of the array. Run this cell
a.ndim

In [ ]:
# ndarray.shape gives the tuple having the shape of the array. Run this cell. 
# Here, you can interpret the shape of a as having 2 rows and 3 columns.
a.shape

In [ ]:
# ndarray.size the total number of elements of the array. This is equal to the product of the elements of shape.
a.size

In [ ]:
# ndarray.dtype an object describing the type of the elements in the array.
a.dtype

In [ ]:
# Create a numpy array having elements [1,2,3,4,5] in first row and [6,7,8,9,10] in the second row. 
b = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(b)
# Find the attributes shown in the above 4 cells.  Write the code below.

In [ ]:
b.ndim

In [ ]:
a.size

In [ ]:
a.dtype

In [ ]:
# Sometimes we want to get an individual dimension of an array.  
# We can index which dimension we want from the shape attribute.
print("To get the first dimension:")
print(a.shape[0])
print("To get the second dimension:")
print(a.shape[1])

# Creating array of zeros and ones.

In [ ]:
# Array of zeros. The code below creates an array of zeros of the specified dimension.
# Code below creates an array of zeros of dimension (3,4)
a=np.zeros((3,4))
print(a)
print(a.dtype)

In [ ]:
# Array of ones. Here, dtype attribute specifies the data type of the elements of array. This is optional. 
# By default, it is float64 as you can see in the example of zeros above.
# Array of ones with dimensions (2,3,4)
b = np.ones( (2,3,4), dtype=np.int16 )
print(b)
print(b.dtype)

In [ ]:
# Create an array of zeros of dimension (5,6) 
a=np.zeros((5,6))
print(a)

In [ ]:
# Create an array of ones of dimension (2,3)
b=np.ones((2,3))
print(b)

# Reshape Function.

Reshape function is used to reshape an array. See the example below. 

In [ ]:
a = np.arange(15)
print("The original array a")
print(a)
print("The array a reshaped with dimensions 3x5")
print(a.reshape(3,5))

In [ ]:
# Reshape function doesn't change the shape of original array. 
print("Notice that a didn't change")
print(a)
print("The dimensions of a:")
print(a.shape)

In [ ]:
# To change the shape of original array, use this. 
a = a.reshape(3,5)
print("Notice a has been changed")
print(a)
print("The new dimensions of a:")
print(a.shape)

In [ ]:
# Create an array of zeros of dimension (4,5)
b= np.zeros((4,5))
print(b)
# Reshape b to dimensions (10,2).
b = b.reshape(10,2)
print(b)

# Note:
Whenever you use a 1 dimensional array, it is a rank 1 array. In the later assignments, you will see that we don't prefer to use rank 1 array. So, we can convert them to rank 2 using reshape function. 

In [15]:
# Run this cell
# Here we have a rank 1 matrix. See it's shape.
a = np.array([1,2,3])
print(a)
print(a.shape)

[1 2 3]
(3,)


In [16]:
# Run this cell
a = a.reshape((3,1))
# Notice that a changed from a sequence of numbers to a sequence of sequence of numbers
print("The new shape of a")
print(a)
print("The array a's new dimensions:")
print(a.shape)

The new shape of a
[[1]
 [2]
 [3]]
The array a's new dimensions:
(3, 1)


# Numpy.random.rand and Numpy.random.randn

In [ ]:
# Numpy.random.rand creates a numpy array of given dimensions where all the elements 
# are random samples from a uniform distribution over [0, 1).
# Run this code cell.
a = np.random.rand(2,3)
print(a)

 Numpy.random.randn creates a numpy array of given dimensions where all the elements are  samples from univariate “normal” (Gaussian) distribution of mean 0 and variance 1

In [ ]:
# Run this cell
a = np.random.randn(2,10)
print(a)

Numpy can create an array having values from the normal distribution with mean = $\mu$, and variance = $\sigma^2$.

To create a random array of elements from $N(\mu, \sigma^2)$, use: sigma = $\sigma$, and mu = $\mu$ and the numpy command:

sigma * np.random.randn(...) + mu

In [ ]:
# Two-by-four array of samples from N(3, 6.25):
a=2.5 * np.random.randn(2, 4) + 3
a

In [ ]:
# Create a numpy array dimension $3\times 5$ containing random samples with mean (mu)= 5 
# and standard deviation(sigma) = 2
b = 2 * np.random.randn(3,5) + 5
print(b)

# Basic Operations: 
Arithmetic operators on arrays apply elementwise. A new array is created and filled with the result.

In [ ]:
# Run this code cell
a = np.array( [20,30,40,50] )
b = np.arange( 1,5 )
print("The array a:")
print(a)
print("The array b:")
print(b)

In [ ]:
# To subtract corresponding elements of array b from array a , simply write a - b as shown below
c = a - b
print(c)

In [ ]:
# similarly we can do addition, multiplication, division of corresponding elements. Complete the code to add, multiply and divide corresponding elements of a and b.
addition = a+b # Add
product = a*b  # Multiply
ratio = a/b    # Divide
print("a + b:")
print(addition)
print("a * b: ")
print(product)
print("a/b:")
print(ratio)

In [ ]:
# Square all the elements of the array b and save it in an array d
d = b**2
print(d)

In [ ]:
# Take sine of all the elements of a matrix and save it in another matrix d
d=10*np.sin(a)
print(d)

In [ ]:
# Run this cell to see how this works
e= a<35
print(e)

# Matrix and vector operations

Unlike in many matrix languages (like matlab), the product operator * operates elementwise in NumPy arrays. The matrix product can be performed using the dot function or the dot method:

In [ ]:
# Run this cell
A = np.array( [[1,1],[0,1]] )
B = np.array( [[2,0], [3,4]] )
print(A)
print(B)

In [ ]:
# Element wise product. Note: Dimensions should be same for A and B
C = A * B
print(C)

In [ ]:
# The dot method for matrix multiplication.
# Dimensions should be in accordance to linear algbra rule of Matrix-Matrix or Matrix-Vector multiplication.
D = A.dot(B) 
print(D)

In [ ]:
# Another way to multiply matrices is to use np.dot() function.
D = np.dot(A,B)
print(D)

In [ ]:
# Create a random matrix of dimension (3,4) and another random matrix of dimension (4,2) and find their dot product. 
# Also, check the dimensions of the resultant matrix.
mat1= np.random.randn(3,4)
mat2= np.random.randn(4,2)
dot_product= np.dot(mat1,mat2)
print("mat1:")
print(mat1)
print("mat2:")
print(mat2)
print("mat1 times mat2:")
print(dot_product)
print("Dimension: ", dot_product.ndim)

Many unary operations, such as computing the sum of all the elements in the array, are implemented as methods of the ndarray class.

In [ ]:
# Run this cell
a = np.random.random((2,3))
print(a)

In [ ]:
# Calculating sum of all the elements of the array. 
# This method considers all the elements of array as a long list of numbers regardless of the shape.
add = a.sum()
print(add)

In [ ]:
# Find minimum and maximum from all the elements using a.min() and a.max() command.
minimum = a.min()
maximum = a.max()
print("minimum = %9.8f"%(minimum))
print("maximum = %9.8f"%(maximum))

In [ ]:
# Create a random array a of dimension (4,6) and find sum , min, max as shown above.
a = np.random.randn(4,6)
add = a.sum()
minimum= a.min()
maximum= a.max()
print("The array a:")
print(a)
print("The sum of all elements of array a: %9.8f"%(add))
print("minimum = %9.8f"%(minimum))
print("maximum = %9.8f"%(maximum))

# Operations on rows or columns

By default, these operations apply to the array as though it were a list of numbers, regardless of its shape. However, by specifying the axis parameter you can apply an operation along the specified axis of an array:

In [ ]:
# Run this cell
B = np.arange(12).reshape(3,4)
print(B)

In [ ]:
# sum along a column
column_sum = B.sum(axis=0)  
print(column_sum)

In [ ]:
# sum along a row. In sum function above, in place of axis=0, pass axis=1
row_sum = B.sum(axis=1)
print("The row sums:")
print(row_sum)
# Minimum along row
min_row= B.min(axis=1)
print("The minimum item in every row:")
print(min_row)
# Minimum along column
min_column= B.min(axis=0)
print("The minimum item in every column:")
print(min_column)

In [ ]:
# To apply universal mathematical functions on all the elements of a matrix, we do so as shown below:
B = np.arange(3)
print("The array B:")
print(B)
# Compute exponent of every element of B
C = np.exp(B) 
print("The array C:")
print(C)
# Compute sqrt of every element in B.  (You may get an error if an element in B is negative.)
D = np.sqrt(B)
print("The array D:")
print(D)

In [ ]:
# Create a random matrix of dimensions (2,4) and apply the above three operations.
A = np.random.randn(2,4)
print("The array A:")
print(A)
# Apply operations on matrix A
B = np.sqrt(A)
print(B)
C = np.exp(A)
print(C)
# Perform np.log( ).  (Note: you will get error if you try to take the log of a negative number.)
D = np.log(A)
print(D)

# Transpose of a Matrix
There are 2 ways to get transpose of a numpy array. Either using .T attribute or using np.transpose(matrix) method.
Note: If you have a rank 1 matrix and you take it's transpose, it will be same as the original matrix.

In [ ]:
# Using .T attribute
A = np.arange(4).reshape((2,2))
B = A.T
print("The original A:")
print(A)
print("The transpose of A:")
print(B)

In [ ]:
# Using transpose method
C = np.transpose(A)
print(C)

In [ ]:
# Create a random matrix X of dimension (4,3) and take it's transpose.
X = np.random.randn(4,3)
# Find transpose of X using any of the above method
Y = np.transpose(X)
print("X: ")
print(X)
print("X Transpose: ")
print(Y)

# Indexing, slicing and iterating

Indexing, slicing and iterating on 1-dimensional arrays. 

Indexing, slicing and iterating is almost same as simple python lists for 1-dimensional arrays. 

Note: Index starts from 0.

In [ ]:
# Run this cell
a = np.arange(15)**3
print(a)

In [ ]:
# Indexing. Getting third element of a
b = a[2]
print(b)
# Find fifth element of a
c = a[4]
print(c)

In [ ]:
# Slicing. Getting elements from index 2 to 5.  (Note we do not get the item at index 6.)
b = a[2:6]
print(b)
# Find elements from index 4 to 7.
c = a[4:6]
print(c)

In [ ]:
# Reversing 1-D array
rev = a[::-1]
print(rev)

In [ ]:
# Looping over some indices.
# Start from index 2, stop before index 12 and jump or increment by 3.
x = a[2:12:3]
print(x)
# Start from index 3, stop before index 12 and jump by 4.
y = a[3:12:4]
print(y)

In [ ]:
# Using a for loop to iterate:
for i in a:
    print(i)

# Multidimensional arrays 
They can have one index per axis. These indices are given in a tuple separated by commas:

In [ ]:
# Run this code
a = np.arange(12).reshape(4,3)
print(a)

In [ ]:
# Element in third row and second column of the matrix.  
# Note due to indexing starting from 0, we use index 2 for the third row and we use index 1 for the second column
print(a[2,1])

In [ ]:
# Find element in second row and third column. 
b = a[1][2]
print(b)

In [ ]:
# Getting each row in the second column of array a
c = a[: , 1]
print(c)

In [ ]:
# Get each column in the second row of a.
d = a[1,:]
print(d)

In [ ]:
# a[i:j, : ] returns rows i+1 through j of the matrix.  (Yeah this is confusing due to indexing starting at 0!)
# In the code below we get rows 2 through 3 of the matrix.  (We index from 1 to (3-1).) 
e = a[1:3, : ]
print(e)

In [ ]:
# Get the last row
b = a[-1,:]
print(b)

In [ ]:
# Find last column
c = a[:,-1]
print(c)

You can use a for loop to traverse through an array!!

In [ ]:
for i in range(a.shape[0]):
    for j in range(a.shape[1]):
        print(a[i][j])

# Stacking together different arrays.

Several arrays can be stacked together along different axes:

In [17]:
# Run this cell
a = np.arange(4).reshape((2,2))
print(a)

[[0 1]
 [2 3]]


In [18]:
# Run this cell
b = np.arange(4,8).reshape((2,2))
print(b)

[[4 5]
 [6 7]]


To stack array b at the bottom of array a, we use vstack command. Note, for vstack, number of columns in both arrays should be same i.e. a.shape[1] == b.shape[1].

In [19]:
# Stacking b at the bottom of a.
c = np.vstack((a,b))
print(c)
print(c.shape)

[[0 1]
 [2 3]
 [4 5]
 [6 7]]
(4, 2)


In [20]:
# Horizontal stack. Stack a to the left of b. 
# Note, for hstack, number of rows in both arrays should be same i.e. a.shape[0] == b.shape[0].
d = np.hstack((a,b))
print(d)

[[0 1 4 5]
 [2 3 6 7]]


In [ ]:
# Create an array a of dimension (3,2) and another array b of dimension (3,5). 
# Append one of them to the left of another i.e. hstack.
a= np.random.randn(3,2)
b= np.random.randn(3,5)
c=  np.hstack((a,b))
print("The array a:")
print(a)
print("The array b:")
print(b)
print("The array c:")
print(c)

# Broadingcasting.

This is an important feature of numpy arrays. Suppose we have an array a of dimension (4,5) and another array b of dimension (4,1). If we want to add both the arrays, is it possible according to linear algebra? The answer is NO because in Linear Algebra, to perform element-wise arithmetic operations, dimensions should be same. 

However, using broadcasting it is possible to add the arrays. Broadcasting copies the first column of b to other columns of b to make it of same size as of a i.e. make it of dimension (4,5) from (4,1). 

In [ ]:
a = np.arange(20).reshape((4,5))
print(a)

In [ ]:
b = np.arange(4).reshape((4,1))
print(b)

In [ ]:
c = a + b
print(c)

For broadcasting to work, all the dimensions must be compatible. A dimension is compatible for both arrays either if  they are equal, or either of them is 1.  

For example: array b has dimensions (2,3,4) and array c has dimensions (1,3,2).  The first dimension is compatible because c.shape[0]=1.  The second dimension is compatible because b.shape[1]==c.shape[1].  But the third dimension is not compatible becaue b.shape[2] $\not =$ c.shape[2] and neither of them is 1.

When operating on two arrays, NumPy compares their shapes element-wise. It starts with the trailing dimensions, and works its way forward. 

When either of the dimensions compared is one, the other is used. In other words, dimensions with size 1 are stretched or “copied” to match the other.
In the following example, both the A and B arrays have axes with length one that are expanded to a larger size during the broadcast operation:

A      (4d array):  8 x 1 x 6 x 1
B      (3d array):      7 x 1 x 5
Result (4d array):  8 x 7 x 6 x 5

Another example:

A      (3d array):  15 x 3 x 5
B      (3d array):  15 x 1 x 5
Result (3d array):  15 x 3 x 5

Broadcasting rules can be confusing. But for now, you only need to know very basic broadcasting which is shown in the code cell above.

# Basic Linear Algebra Operations.

In [ ]:
a = np.array([[1.0, 2.0], [3.0, 4.0]])
print(a)

In [ ]:
# To find Inverse of matrix a:
b = np.linalg.inv(a)
print(b)

In [ ]:
# Creating Identity matrix: Identity matrix is always a square matrix.
u = np.eye(3)
print(u)

In [ ]:
# Finding Trace of a matrix
c = np.trace(u)
print(c)

In [ ]:
# Find eigen values of a matrix
d = np.linalg.eig(a)
print(d)

# Automatic Reshaping

In [ ]:
# Run this cell
a = np.arange(30)
a.shape = 2,-1,3  # -1 means "whatever is needed"
print(a.shape)
print(a)

This assignment ends here. We hope this assignment gives you basic knowledge of using numpy and it's arrays and perform basic operations. We highly encourage you to use official numpy documentation if you need more help while solving your machine learning assignments. https://docs.scipy.org/doc/numpy-dev/user/quickstart.html . One of the topic not covered in this assignment is indexing with arrays of indices and indexing with  boolean arrays. Though not used much in the programming assignments, but can be helpful in some scenarios. You can find them in the given link above.